# Generated by Django 4.0.3 on 2022-04-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_T',
            fields=[
                ('DeptID', models.CharField(max_length=6, primary_key=b'I01\n', serialize=False)),
                ('DeptName', models.CharField(max_length=50, null=b'I01\n')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_T',
            fields=[
                ('FacultyID', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('FacultyName', models.CharField(max_length=50)),
                ('DeptID', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='RCRAS.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Room_T',
            fields=[
                ('RoomID', models.CharField(max_length=9, primary_key=b'I01\n', serialize=False)),
                ('RoomCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School_T',
            fields=[
                ('SchoolTitle', models.CharField(max_length=5, primary_key=b'I01\n', serialize=False)),
                ('SchoolName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='department_t',
            name='SchoolTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCRAS.school_t'),
        ),
        migrations.CreateModel(
            name='Course_T',
            fields=[
                ('CourseID', models.CharField(max_length=7, primary_key=b'I01\n', serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('CreditHour', models.IntegerField()),
                ('DeptID', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='RCRAS.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Section_T',
            fields=[
                ('SectionID', models.CharField(max_length=40, primary_key=b'I01\n', serialize=False)),
                ('SectionNum', models.IntegerField()),
                ('Semester', models.CharField(max_length=6)),
                ('Year', models.IntegerField()),
                ('SectionCapacity', models.IntegerField(null=b'I01\n')),
                ('SectionEnrolled', models.IntegerField(null=b'I01\n')),
                ('StartTime', models.TimeField(null=b'I01\n')),
                ('EndTime', models.TimeField(null=b'I01\n')),
                ('Day', models.CharField(max_length=10, null=b'I01\n')),
                ('Blocked', models.CharField(max_length=3, null=b'I01\n')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCRAS.course_t')),
                ('FacultyID', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='RCRAS.faculty_t')),
                ('RoomID', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='RCRAS.room_t')),
            ],
            options={
                'unique_together': {('SectionNum', 'Semester', 'Year', 'CourseID')},
            },
        ),
        migrations.CreateModel(
            name='CoOfferedCourse_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coofferredwith', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='Coofferredwith', to='RCRAS.course_t')),
                ('OfferedCourseID', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='OfferedCourseID', to='RCRAS.course_t')),
            ],
            options={
                'unique_together': {('OfferedCourseID', 'Coofferredwith')},
            },
        ),
    ]
